name: Laravel API CI

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/laravel.yml'
  pull_request:
    paths:
      - 'api/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, pdo_mysql
          coverage: xdebug

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migration
        run: php artisan migrate
        env:
          DB_HOST: 127.0.0.1

      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit --coverage-text
        env:
          DB_HOST: 127.0.0.1

      - name: PHP Code Style (Laravel Pint)
        run: vendor/bin/pint --test
