name: React Client CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/react.yml'
  pull_request:
    paths:
      - 'client/**'

jobs:
  react-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Type check
        run: tsc --noEmit

      - name: Build
        run: npm run build
